name: release
# on: [workflow_dispatch]
on: [push]
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "7.11.0"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.17.0"
      - run: pnpm i --frozen-lockfile
      - run: npm run tsc
      - run: npm run build
      - run: npm run package
      - name: set PACKAGE_VERSION
        run: echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.PACKAGE_VERSION }}
          tag_name: ${{ env.PACKAGE_VERSION }}
          files: |
            build/latest-linux.yml
            build/*.AppImage
